#!/bin/bash


#SBATCH --job-name=performance_of_simclr_on_tcga
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=3
#SBATCH --partition=gpu_shared
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=2:00:00
#SBATCH --mem=62GB
#SBATCH --array=1-5
# moved into jobs/msi dir, nothing should change besides this

module purge
module load 2019

module load Anaconda3
module load CUDA/10.0.130
module load cuDNN/7.6.3-CUDA-10.0.130
export LD_LIBRARY_PATH=/hpc/eb/Debian9/cuDNN/7.6.3-CUDA-10.0.130/lib64:$LD_LIBRARY_PATH

CONDA_PREFIX=$(conda info --base)
source $CONDA_PREFIX/etc/profile.d/conda.sh
conda activate thesisp375

cd ..

# VARIABLES
INCLUDEFILE=/home/yonis/histogenomics-msc-2019/yoni-code/MsiPrediction/metadata/tcga/crc_dx/paths_for_train_and_test.txt
ORIGINAL_DATA_PATH=/home/yonis/tcga_breast_ddr
TMP_PARENT_DIR_FOR_DATA=msidata # is required for the msi dataset to know the task

echo "starting to copy to scratch..."
date
#cp /home/yonis/tcga_breast_ddr/tiled_data_large.tar.gz "$TMPDIR"
#rsync -a -progress=info2 --exclude "json" $ORIGINAL_DATA_PATH "$TMPDIR"
#rsync -a -progress=info2 --exclude "json" --files-from=$INCLUDEFILE $ORIGINAL_DATA_PATH "$TMPDIR"
#rsync -ah --delete --ignore-existing --exclude "*.pt" $ORIGINAL_DATA_PATH "$TMPDIR"/
echo "done with copying to scratch..."
date
cd "$TMPDIR"
#tar xzf tiled_data_large.tar.gz
echo "done with unzipping"
date
ls "$TMPDIR"
cd -


num_workers=6
echo "Num threads: $num_workers"

#srun python3 -u -m testing.logistic_regression with workers=$num_workers config_file=./config/test-tcga-crc-4gpu.yaml root_dir_for_tcga_tiles="$TMPDIR"/tiled_data_large/ use_multi_gpu=False pretrain=False
#srun python3 -u -m testing.logistic_regression with workers=$num_workers config_file=./config/test-tcga-brca.yaml use_multi_gpu=False pretrain=False precompute_features=True precompute_features_in_memory=False 
#array=('PARPi7_bin' 'median_mutLoad_silent' 'median_mutLoad_nonsilent' 'median_tp53_score' 'median_rppa_ddr_score' 'median_HRD_Score' 'median_purity' 'median_ploidy' 'median_CNA_frac_altered' 'BER' 'NER' 'MMR' 'FA' 'HDR' 'NHEJ' 'DR' 'TLS' 'NP' 'Others' 'core-BER' 'core-NER' 'core-MMR' 'core-FA' 'core-HR' 'core-NHEJ' 'core-DR' 'core-TLS' 'core-DS' 'any-mut' 'any-base' 'any-mmr' 'any-strand' 'core-base' 'core-mrr' 'core-strand' 'core-mmr-and-hr')
#for i in "${array[@]}"
#do
#done

srun python3 -u -m testing.logistic_regression with workers=6 config_file=./config/test-tcga-brca.yaml precompute_features=False use_precomputed_features=True use_precomputed_features_id=437 logistic_epochs=5 ddr_label="median_HRD_Score" evaluate_every=100 kfold=$SLURM_ARRAY_TASK_ID
#rsync -a -progress=info2 --ignore-existing --exclude="*.jpg" "$TMPDIR"/tiled_data_large/ "$ORIGINAL_DATA_PATH"/tiled_data_large/ 
