seed: 42
workers: 12
dataset: "msi-kather"
#path_to_msi_data: "/Users/yoni/dropbox/UvA/AI/nki/histogenomics-msc-2019/yoni-code/MsiPrediction/data/msidata/crc_dx/train/"
#path_to_test_msi_data: "/Users/yoni/dropbox/UvA/AI/nki/histogenomics-msc-2019/yoni-code/MsiPrediction/data/msidata/crc_dx/test/"
path_to_msi_data: "/home/yonis/histogenomics-msc-2019/yoni-code/MsiPrediction/data/msidata/crc_dx/train/"
path_to_test_msi_data: "/home/yonis/histogenomics-msc-2019/yoni-code/MsiPrediction/data/msidata/crc_dx/test/"

load_patient_level_tensors: True
data_testing_train_fraction: 1


reload_model: False
model_path: "logs/pretrain/271" # set to the directory containing `checkpoint_##.tar` 
epoch_num: 42 # set to checkpoint number. Should be the one with highest validation ROCAUC

classification_head: 'deepmil' # or 'logistic' or 'deepmil'
logistic_batch_size: 1

use_precomputed_features: True
use_precomputed_features_id: '1'
validation_split: 0.2

pretrain: False

fp16: False
optimizer: "Adam"
