data_create_feature_vectors_fraction: 1
data_testing_train_fraction: 1
kfold: 1 # since we have train, test, and val, this'll do ALL data.

model_path: ./logs/pretrain/585
epoch_num: 68040
use_precomputed_features: False
path_to_msi_data: /project/schirris/basisscripts/step_3/data_basis_brca_with_labels_and_splits.csv
dataset: basis
create_feature_grid: True
reload_model: True
optimizer: Adam
batch_size: 128
fp16: False
pretrain: False
root_dir_for_tcga_tiles: /project/schirris/tiled_data_large/
resnet: shufflenetv2_x1_0
projection_hidden: 128
projection_dim: 128
unsupervised_method: simclr
normalize: True


feature_learning: unsupervised
