data_create_feature_vectors_fraction: 1
model_path: doesnt_matter_for_now
use_precomputed_features_id: 950
path_to_msi_data: /home/yonis/histogenomics-msc-2019/yoni-code/MsiPrediction/metadata/tcga/brca_dx/data_tcga_brca_dxwith_ddr_labels_and_splits_dropna_subsample_500.csv
create_feature_grid: True
pretrain: False
use_precomputed_features: True
dataset: msi-tcga
root_dir_for_tcga_tiles: /project/yonis/tcga_brca_dx/tiled_data_large/
